app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('savat/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

app/orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
 path('create/', views.order_create, name='order_create'),
]

app/product/urls.py
from django.urls import path
from . import views
app_name = 'product'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
    path('product/<str:id>/<slug:slug>/', views.product_detail,name='product_detail'),
]

app/users/urls.py
from django.urls import path  
from django.contrib.auth import views as auth_views
from .views import *

app_name='users'

urlpatterns = [
    path('sigin/',LoginPage, name="sigin"),
    path('signup/', RegisterPage, name="signup"),
    path("signout/",LogoutPage, name="signout"),
    path('profile/', profile, name='profile'),
    path('edit/',edit, name='edit'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),

    path("password_change/",password_change, name="password_change"),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', passwordResetConfirm, name='password_reset_confirm'),
]

app/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Electro - HTML Ecommerce Template</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
    {% include 'base/navbar.html' %}
    {% block content %}{% endblock content %}
    {% include 'base/footer.html' %}
      <!-- Swiper JS -->
		<!-- jQuery Plugins -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

app/templates/base/footer.html
		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="#">Hot deals</a></li>
									<li><a href="#">Laptops</a></li>
									<li><a href="#">Smartphones</a></li>
									<li><a href="#">Cameras</a></li>
									<li><a href="#">Accessories</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Information</h3>
								<ul class="footer-links">
									<li><a href="#">About Us</a></li>
									<li><a href="#">Contact Us</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Orders and Returns</a></li>
									<li><a href="#">Terms & Conditions</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Service</h3>
								<ul class="footer-links">
									<li><a href="#">My Account</a></li>
									<li><a href="#">View Cart</a></li>
									<li><a href="#">Wishlist</a></li>
									<li><a href="#">Track My Order</a></li>
									<li><a href="#">Help</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

app/templates/base/navbar.html
{% load static %}
<header>
  <!-- TOP HEADER -->
  <div id="top-header">
    <div class="container">
      <ul class="header-links pull-left">
        <li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
        <li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
        <li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
      </ul>
      <ul class="header-links pull-right">
        <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
        <li><a href= "{% url 'users:profile' %}"><i class="fa fa-user-o"></i> My Account</a></li>
      </ul>
    </div>
  </div>
  <!-- /TOP HEADER -->

  <!-- MAIN HEADER -->
  <div id="header">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- LOGO -->
        <div class="col-md-3">
          <div class="header-logo">
            <a href="#" class="logo">
              <img src="./img/logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- /LOGO -->

        <!-- SEARCH BAR -->
        <div class="col-md-6">
          <div class="header-search">
            <form action="" method="GET" >
              <select class="input-select">
                
                <option >Barcha Toifalar</option>
                {% for cate in category %}
                <a href="{{ cate.get_absolute_url }}"><option >{{ cate.name }}</option></a>
                {% endfor %}
              </select>
              <input name="q" class="input" placeholder="Bu yerdan qidiring">
              <button type="submit" class="search-btn">Qidirish</button>
            </form>
          </div>
        </div>
        <!-- /SEARCH BAR -->

        <!-- ACCOUNT -->
        <div class="col-md-3 clearfix">
          <div class="header-ctn">
            <!-- Wishlist -->
            
            <!-- /Wishlist -->

            <!-- Cart -->
            <div class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                <i class="fa fa-shopping-cart"></i>
                {% comment %} <span>Your Cart</span> {% endcomment %}
                {% with total_items=cart|length %}
                {% if total_items > 0 %}
                <div class="qty">{{total_items}}</div>
                {% endif %}
                 {% endwith %}
              </a>
              <div class="cart-dropdown">
                <div class="cart-list">
                  {% for item in cart %}
                  {% with product=item.product %}
                  <div class="product-widget">
                    <div class="product-img">
                      <img src="{{product.image.url}}" alt="">
                    </div>
                    <div class="product-body">
                      <h3 class="product-name"><a href="{{ product.get_absolute_url}}">{{product.name}}</a></h3>
                      <h4 class="product-price"><span class="qty">{{item.quantity }}x</span>{{product.price}} ming So'm</h4>
                    </div>
                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="delete"><i class="fa fa-close"></i></button>
                    </form>
                  </div>
                  {% endwith %}
                  {% endfor %}
                </div>
                <div class="cart-summary">
                  <small>3 Item(s) selected</small>
                  <h5>Jami:{{ cart.get_total_price }} ming So'm</h5>
                </div>
                <div class="cart-btns">
                  {% if  request.path != "/cart/savat/" %}
                  <a href="{% url 'cart:cart_detail' %}">              
                        Savatni ko'rish
                  </a>
                  {% else %}
                  <a href="{% url 'product:product_list' %}">
                    Bosh Sahifa
                 </a>
                  {% endif %}
                  {% if  request.path != "/orders/create/" %}
                  <a href="{% url 'orders:order_create' %}">Buyurtma<i class="fa fa-arrow-circle-right"></i></a>
                  {% else %}
                  <a href="{% url 'product:product_list' %}">

                    Bosh Sahifa
                    <i class="fa fa-arrow-circle-right"></i>
                 </a>
                  {% endif %}
                </div>
              </div>
            </div>
            <!-- /Cart -->

            <!-- Menu Toogle -->
            <div class="menu-toggle">
              <a href="#">
                <i class="fa fa-bars"></i>
                {% comment %} <span>Menu</span> {% endcomment %}
              </a>
            </div>
            <!-- /Menu Toogle -->
          </div>
        </div>
        <!-- /ACCOUNT -->
      </div>
      <!-- row -->
    </div>
    <!-- container -->
  </div>
  <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->

<!-- NAVIGATION -->
<nav id="navigation">
  <!-- container -->
  <div class="container">
    <!-- responsive-nav -->
    <div id="responsive-nav">
      <!-- NAV -->
      <ul class="main-nav nav navbar-nav">
         <!-- Menu Toogle -->
    <!-- /Menu Toogle -->
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Hot Deals</a></li>
        <li><a href="#">Categories</a></li>
        <li><a href="#">Laptops</a></li>
        <li><a href="#">Smartphones</a></li>
        <li><a href="#">Cameras</a></li>
        <li><a href="#">Accessories</a></li>
      </ul>
      <!-- /NAV -->
    </div>
    <!-- /responsive-nav -->
  </div>
  <!-- /container -->
</nav>
<!-- /NAVIGATION -->

<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!-- shop -->
      <div class="col-md-4 col-xs-6">
        <div class="shop">
          <div class="shop-img">
            <img src="./img/shop01.png" alt="">
          </div>
          <div class="shop-body">
            <h3>Laptop<br>Collection</h3>
            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>
      <!-- /shop -->

      <!-- shop -->
      <div class="col-md-4 col-xs-6">
        <div class="shop">
          <div class="shop-img">
            <img src="./img/shop03.png" alt="">
          </div>
          <div class="shop-body">
            <h3>Accessories<br>Collection</h3>
            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>
      <!-- /shop -->

      <!-- shop -->
      <div class="col-md-4 col-xs-6">
        <div class="shop">
          <div class="shop-img">
            <img src="./img/shop02.png" alt="">
          </div>
          <div class="shop-body">
            <h3>Cameras<br>Collection</h3>
            <a href="#" class="cta-btn">Shop now <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>
      <!-- /shop -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->